base_url = "https://laconicd.github.io"
title = "The Blog"
description = "A blog about Rust, Zola, and modern web development. Featuring tutorials, insights, and personal projects."
build_search_index = true
default_language = "ko"
minify_html = true

taxonomies = [
    {name = "tags"},
    {name = "categories"},
]

[search]
include_title = true
include_description = true
include_date = true
include_path = true
include_content = true
index_format = "fuse_javascript"

[markdown]
highlight_code = true
highlight_theme = "css"
render_emoji = true

[extra]
hero_title = "Writings"
hero_subtitle = "The latest news, technologies, and resources from our team."
default_image = "default_og.png"
date_format = "%B %d, %Y"
author_name = "My Name"
author_role = "Writer"
author_avatar = "images/avatar.svg"
